mongoimport --db amazon --collection Home_and_Kitchen_corpus ../AmazonDataset/processed_rv/reviews_Home_and_Kitchen_corpus2.json
mongoimport --db amazon --collection Sports_and_Outdoors_corpus ../AmazonDataset/processed_rv/reviews_Sports_and_Outdoors_corpus2.json
mongoimport --db amazon --collection Automotive_corpus ../AmazonDataset/processed_rv/reviews_Automotive_corpus2.json
mongoimport --db amazon --collection Baby_corpus ../AmazonDataset/processed_rv/reviews_Baby_corpus2.json
mongoimport --db amazon --collection Beauty_corpus ../AmazonDataset/processed_rv/reviews_Beauty_corpus2.json
mongoimport --db amazon --collection Office_Products_corpus ../AmazonDataset/processed_rv/reviews_Office_Products_corpus2.json
mongoimport --db amazon --collection Clothing_Shoes_and_Jewelry_corpus ../AmazonDataset/processed_rv/reviews_Clothing_Shoes_and_Jewelry_corpus2.json
mongoimport --db amazon --collection Toys_and_Games_corpus ../AmazonDataset/processed_rv/reviews_Toys_and_Games_corpus2.json
mongoimport --db amazon --collection Musical_Instruments_corpus ../AmazonDataset/processed_rv/reviews_Musical_Instruments_corpus2.json
mongoimport --db amazon --collection Pet_Supplies_corpus ../AmazonDataset/processed_rv/reviews_Pet_Supplies_corpus2.json
mongoimport --db amazon --collection Health_and_Personal_Care_corpus ../AmazonDataset/processed_rv/reviews_Health_and_Personal_Care_corpus2.json
mongoimport --db amazon --collection Books_corpus ../AmazonDataset/processed_rv/reviews_Books_corpus2.json
mongoimport --db amazon --collection Electronics_corpus ../AmazonDataset/processed_rv/reviews_Electronics_corpus2.json
mongoimport --db amazon --collection Movies_and_TV_corpus ../AmazonDataset/processed_rv/reviews_Movies_and_TV_corpus2.json